spring:
  datasource:
    url: jdbc:mysql://localhost:3306/documents
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
format_sql: true
server:
  port: 9090  
  error:
    path: /error

